# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8418974f0e37d296b601e36178e8b89f13ca6ad1e1b0374822edccc934f2837990af2673234db2e29044968c59e0dc5187c5f52a786b2eb688fc316431111f72

test:
  secret_key_base: f2c55d52f3cb322904ee7f753cd640e4871cd9ece0c28010221eea25c398a84c8897b397628c60dfc6a1d45b8984de694455efb5ca71615d28dbf3039c055d56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
